# Generated by Django 6.0.5 on 2026-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='naver_id',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
    ]
