# Generated by Django 6.0.5 on 2026-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_options_alter_restaurant_naver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='naver_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
